daengtionary/Frontend

- public/index.html
- src/components/map/map.js
- src/components/map/map.styled.js
- src/pages/detail/Detail.js
> feat: kakao 지도 API 연결, map 모달 제작, detail 페이지 html 작성

- package.json
- public/index.html
- src/components/map/map.js
- yarn.lock
> refactor: key 재발급 후 환경변수로 적용

- src/App.js
- src/components/footer/Footer.js
- src/components/footer/Footer.styled.js
- src/pages/main/Main.js
- src/pages/mypage/MyPage.js
- src/pages/signin/SignIn.js
- src/pages/signup/SignUp.js
- src/redux/configStore.js
fix: main reducer 오타로 인한 문제 수정,style: Header, Footer 컴포넌트 위치 변경
> fix: main reducer 오타로 인한 문제 수정,style: Header, Footer 컴포넌트 위치 변경

- package.json
- src/App.js
- src/components/card/ListPageCard.js
- src/pages/animalhospital/List.js
- src/pages/main/Main.js
- src/pages/mypage/MyPage.js
- src/redux/modules/listSlice.js
- src/redux/modules/mainSlice.js
- src/redux/modules/myPageSlice.js
- src/shared/ScrollToTop.js
- yarn.lock
feat: 무한스크롤 구현 중, 라우팅 이후 스크롤 위치 조정, 마이페이지 접근시 토큰 검증
> feat: 무한스크롤 구현 중, 라우팅 이후 스크롤 위치 조정, 마이페이지 접근시 토큰 검증

- src/App.js
- src/components/card/TradeCard.js
- src/components/card/TradeCard.styled.js
- src/components/chatFloatButton/ChatFloatButton.js
- src/components/chatFloatButton/ChatFloatButton.styled.js
- src/components/chatModal/ChatModal.js
- src/components/chatRoomList/ChatRoomList.js
- src/elements/svg/SVG.js
- src/pages/animalhospital/List.js
- src/pages/signup/SignUp.js
- src/pages/signup/SignUp.styled.js
- src/pages/trade/Trade.js
- src/pages/trade/Trade.styled.js
- src/pages/tradeDetail/TradeDetail.js
- src/pages/tradeDetail/TradeDetail.styled.js
- src/redux/modules/tradeSlice.js
- src/shared/api.js
feat: 장터 페이지, 장터 디테일, 장터 아이템 카드 페이지 조회 기능 추가 /style: 스타일 추가
> feat: 장터 페이지, 장터 디테일, 장터 아이템 카드 페이지 조회 기능 추가 /style: 스타일 추가

- src/components/chatFloatButton/ChatFloatButton.js
- src/components/chatModal/ChatModal.js
- src/components/chatRoomList/ChatRoomList.js
- src/redux/modules/chatSlice.js
refactor: 채팅룸 리스트 불러오기 api 주소 수정
> refactor: 채팅룸 리스트 불러오기 api 주소 수정

- src/elements/input/Input.js
- src/pages/animalhospital/List.js
- src/pages/mypage/MyPage.js
- src/redux/modules/listSlice.js
feat: 마이페이지 nick input 키 입력시 자동 수정모드로 진입되게 변경,
fix: 리스트페이지 게시물 수 적어서 무한스크롤 동작 안 하는 문제 수정
> feat: 마이페이지 nick input 키 입력시 자동 수정모드로 진입되게 변경, fix: 리스트페이지 게시물 수 적어서 무한스크롤 동작 안 하는 문제 수정

- my-app/package.json
- src/components/header/Header.styled.js
- src/pages/animalhospital/List.js
- src/pages/main/Main.js
- src/pages/trade/Trade.js
> fix: 병합 후 발생 오류 해결

- src/pages/main/Main.js
- src/pages/tradePosting/TradePosting.js
- src/redux/modules/mainSlice.js
> fix: 병합 후 오류 수정(api 호출 누락)

- src/pages/detail/Detail.js
- src/pages/detail/Detail.styled.js
- src/pages/tradePosting/TradePosting.js
- src/shared/showStars.js
shared 폴더 아래 showStars 함수 작성 후 export 함
> feat: 별점 표시 함수 따로 작성함

- src/components/card/ListPageCard.js
- src/pages/animalhospital/List.js
- src/pages/placePosting/PlacePosting.js
- src/redux/modules/placeSlice.js
fix: posting 이후에 바로 붙지 않는 문제상황 수정
> fix: posting 이후에 바로 붙지 않는 문제상황 수정

- src/App.js
- src/components/card/Card.styled.js
- src/components/card/ListPageCard.js
- src/components/card/TradeCard.js
- src/components/dogAddModal/DogAddModal.js
- src/index.css
- src/pages/animalhospital/List.js
- src/pages/mypage/MyPage.js
- src/pages/tradeDetail/TradeDetail.styled.js
> style:'병합 후 세부적인 스타일 수정'

- src/components/card/Card.styled.js
- src/components/card/ListPageCard.js
- src/components/dogAddModal/DogAddModal.js
- src/pages/animalhospital/List.js
- src/pages/main/Main.js
- src/pages/placePosting/PlacePosting.js
> style: place 포스팅 반응형 디자인 추가

- src/components/card/Card.js
- src/components/card/Card.styled.js
- src/pages/main/Main.js
fix: 메인페이지 애견호텔 카드 navigate 작동 안 하는 문제 해결,style: 메인 페이지 카드 의도치 않은 트랜지션 적용된 부분 수정
> fix: 메인페이지 애견호텔 카드 navigate 작동 안 하는 문제 해결,style: 메인 페이지 카드 의도치 않은 트랜지션 적용된 부분 수정

- src/components/card/Card.js
- src/components/card/Card.styled.js
- src/components/card/ListPageCard.js
- src/redux/modules/listSlice.js
style: 메인/리스트 페이지 카드 텍스트가 영역 넘어가는 문제 해결, 반응형 전환 시 폰트 사이즈 조정,fix:리스트 페이지 스크롤 안 되던 문제 해결
> style: 메인/리스트 페이지 카드 텍스트가 영역 넘어가는 문제 해결, 반응형 전환 시 폰트 사이즈 조정,fix:리스트 페이지 스크롤 안 되던 문제 해결

- src/components/card/MatchingCard.js
- src/components/card/MatchingCard.styled.js
- src/pages/matching/Matching.js
- src/pages/matching/MatchingDetail.js
- src/pages/trade/Trade.js
- src/pages/trade/Trade.styled.js
- src/pages/tradeDetail/TradeDetail.js
style: 장터페이지 카드 간격, 장터디테일 스와이프 이미지 변경, feat:  매칭페이지 카드 서버 연결
> style: 장터페이지 카드 간격, 장터디테일 스와이프 이미지 변경, feat:  매칭페이지 카드 서버 연결

- src/components/dogAddModal/DogAddModal.js
- src/pages/mypage/MyPage.js
style: 마이페이지 모달 위치 조정 테스트,마이페이지 닉네임 수정버튼 폰트 사이즈 조정
> style: 마이페이지 모달 위치 조정 테스트,마이페이지 닉네임 수정버튼 폰트 사이즈 조정

- src/components/dogAddModal/DogAddModal.js
> style: 모달 위치 테스트2

- src/pages/main/Main.js
> style: 매칭 페이지 접근 임시 차단

- src/components/PostModal/PostModal.styled.js
- src/components/communityCard/CommunityCard.js
- src/components/communityCard/CommunityCard.styled.js
- src/components/communityDetialRipleCard/CommunityDetailRipleCard.js
- src/components/communityPost/CommunityPost.js
- src/components/communityPost/CommunityPost.styled.js
- src/components/footer/Footer.js
- src/components/map/Map.js
- src/components/searchBar/SearchBar.js
- src/pages/community/Community.js
- src/pages/community/Community.styled.js
- src/pages/communityDetail/CommunityDetail.js
- src/pages/communityDetail/CommunityDetail.styled.js
- src/pages/detail/Detail.js
- src/pages/detail/Detail.styled.js
- src/pages/main/Main.js
- src/redux/modules/communitySlice.js
- src/redux/modules/detailSlice.js
필요없는 변수, 함수, 주석, console.log( ) 삭제
> refactor: 코드 리팩토링

- src/App.js
- src/components/card/Card.js
- src/components/card/ListPageCard.js
- src/components/dogAddModal/DogAddModal.js
- src/pages/animalhospital/List.js
- src/pages/main/Main.js
- src/pages/mypage/MyPage.js
- src/pages/placePosting/PlacePosting.js
- src/redux/modules/listSlice.js
- src/redux/modules/mainSlice.js
- src/redux/modules/placeSlice.js
- src/shared/TopButton.js
refactor: 주석, log  삭제 / 안 쓰이는 import 및 코드 삭제
> refactor: 주석, log  삭제 / 안 쓰이는 import 및 코드 삭제
